name: API Tests - RestAssured

on: [push, pull_request]

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          java-version: '23'
          distribution: 'temurin'

      - name: Run API Tests with Maven
        run: mvn clean test
        continue-on-error: true

      - name: Gera o relatório do Allure
        run: mvn allure:report
        continue-on-error: true

      - name: Upload RestAssured Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: target/allure-report

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages  # default: gh-pages
          publish_dir: target/allure-report
          destination_dir: allure-report